# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/product.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protos/product.proto\x12\x07product\x1a\x1bgoogle/protobuf/empty.proto\"r\n\x07product\x12\x11\n\tproductId\x18\x01 \x01(\t\x12\x13\n\x0bproductName\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x02\x12\x0b\n\x03tax\x18\x04 \x01(\x02\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x0e\n\x06status\x18\x06 \x01(\t\"\x1e\n\tproductId\x12\x11\n\tproductId\x18\x01 \x01(\t2\xb1\x02\n\x0eproductService\x12\x35\n\rcreateProduct\x12\x10.product.product\x1a\x12.product.productId\x12\x32\n\ngetProduct\x12\x12.product.productId\x1a\x10.product.product\x12\x39\n\rupdateProduct\x12\x10.product.product\x1a\x16.google.protobuf.Empty\x12;\n\rdeleteProduct\x12\x12.product.productId\x1a\x16.google.protobuf.Empty\x12<\n\x0egetAllProducts\x12\x16.google.protobuf.Empty\x1a\x10.product.product0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.product_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PRODUCT']._serialized_start=62
  _globals['_PRODUCT']._serialized_end=176
  _globals['_PRODUCTID']._serialized_start=178
  _globals['_PRODUCTID']._serialized_end=208
  _globals['_PRODUCTSERVICE']._serialized_start=211
  _globals['_PRODUCTSERVICE']._serialized_end=516
# @@protoc_insertion_point(module_scope)
